### ISSUE TITLE
can't find how to make users specs

### ISSUE THREAD

**Issue by ghost** [the-teacher/the_comments#20]
I just resolve how to add, from the linked management, an ability of manage comments (for do it, i just copy/past the link from view/layout/apllication.html to the managed link on my user-nav, and the admin.html.haml from dummyApp to my app/view/layout of my own app...)

But i can't arrive to make a link between my admin user Devise/cancan registration and the real admin user of The_comments gem (so, i not understand really how this works... that's why). I just make a special modification on the _form.html.haml for having the name and email of my current_user value write inside my text_field and readonly option validate when i have a current_user registred (for do it, i just add some condition in the haml file in rails code for choose between normal text_fiel call and mine default entry and readonly inside fields).

Also, when i arrive on the "show" movie (or post if you prefer) page, i see all the comments (also this who are not published). If i'm not sign-in it is the same...
Also, only the form change from published or not.

And then, when i post a comment, i have two times the same comment posted (a copy automatically added).

Also, i can see that this gem "plugin" on my app can be view on Chrome web browser, but not from Firefox.

Please, could someone have an (or some) idea about how to "resolve" all of this problem (or one of this) ?

**Comment by jerome2** [comment]
sorry, i just read now, but yes, it was the problem you tell me. Thanks again.

**Comment by jakeatwork** [comment]
@the-teacher i'm actually having a similar problem with the comments showing multiple when submitted, but the duplicates (sometimes there is more than just one extra) disappear when the page is reloaded. i'm not initializing the JS twice in the application.js - just once for thecomments and once for thecomments_manage. any help appreciated. i recently added the jquery cookie js if that has any known implications.
