### ISSUE TITLE
State machine warning if default state changed in config

### ISSUE THREAD

**Issue by dept42** [the-teacher/the_comments#35]
I set the config to have comments published by default:

```ruby
config.default_state       = :published              # default state for comment
```

This resulted in a warning from state machine about conflicting defaults. The warning went away when I rolled back the migration creating comments, and removed the schema default for the state column.

**Comment by the-teacher** [comment]
So. TheComments 3.0 finished. 

I test it and now this code doesn't work for me. I still working.

```ruby
state_machine :state, initial: TheCommentsBase.config.default_state do
  # ....
end
```

**Comment by the-teacher** [comment]
Hello!
TheComments 2.X now is not interesting for me. v3.0 coming soon. I working on release.
Now code is finished. I planing to write docs in nearest future and relese this gem.

Described problem placed in State Machine gem. Right now `initial` param doesn't work properly. I solved it with following lines

```ruby
      # STATES: %w[ draft published deleted ]
      # Please, keep field `state` blank
      # Reason: the_comments_base/app/models/concerns/the_comments_base/comment_states.rb:10
      t.string :state, default: ''
```
and

```ruby
    included do
      # STATES: :draft | :published | :deleted

      # StateMachine - known issue
      # `initial` param doesn't work
      # `initial: TheCommentsBase.config.default_state`
      # solved with `before_save` method and blank value in migration

      before_save do
        self.state = TheCommentsBase.config.default_state if self.state.blank?
      end

      state_machine :state do
        # events
        event :to_draft do
          transition all - :draft => :draft
        end
   
   #...

end
```

If yyou need - you can copy this code into your project, and it have to work with TheComments 2.X
Now I close this issue. 

PS: You can study TheComments v3.0 here - https://github.com/TheComments (doc not finished)
