### ISSUE TITLE
Comments displaying multiple times, but only one remains after page reload

### ISSUE THREAD

**Issue by jakeatwork** [the-teacher/the_comments#38]
i'm having a problem with the comments showing multiple when submitted, but the duplicates (sometimes there is more than just one extra) disappear when the page is reloaded. i'm not initializing the JS twice in the application.js - just once for thecomments and once for thecomments_manage. any help appreciated. i recently added the jquery cookie js if that has any known implications. oh and added activeadmin as well.

Screenshot below:
https://www.dropbox.com/s/5r5lpmxvh1r7nds/Screenshot%202015-03-02%2017.32.26.png?dl=0

**Comment by the-teacher** [comment]
Can we debug it together with skype or hangouts video conference? It's interesting problem, but I have to deep into comtext to find a solution

**Comment by the-teacher** [comment]
@jakeatwork 

I saw into your application.js

//= require the_comments
...
//= require_tree .

You copied the_comments.js from gem and I think now it required twice

try to remove `//= require the_comments`

**Comment by jakeatwork** [comment]
ok...so i'll mark this as closed.

was going back through old commits looking for timing and clues. found a commit where i added:   

    https://github.com/kossnocorp/jquery.turbolinks

i just removed, recompiled assets, reloaded server…and commented 8 times without a single duplication.

there is a troubleshooting guide on the jquery turbolinks page specifically for this issue.

apologies for the trouble, but really appreciate your help and attention.
