### ISSUE TITLE
Issue with Sidekiq 

### ISSUE THREAD

**Issue by swaathi** [the-teacher/the_comments#39]
I just started Sidekiq and this issue occurred. The Comments was working perfectly all this time. Today I tried to implement Sidekiq in my project (which I've done for other projects before), and I was unable to even start it.

```
I, [2015-04-29T19:03:27.365621 #66653]  INFO -- : ** [Raven] Raven 0.13.1 ready to catch errors
/Users/swaathi/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/the_comments-2.2.2/app/controllers/concerns/controller.rb:2: warning: already initialized constant TheComments::COMMENTS_COOKIES_TOKEN
/Users/swaathi/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/the_comments-2.2.2/app/controllers/concerns/controller.rb:2: warning: previous definition of COMMENTS_COOKIES_TOKEN was here
Cannot define multiple 'included' blocks for a Concern
/Users/swaathi/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/concern.rb:126:in `included'
/Users/swaathi/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/the_comments-2.2.2/app/controllers/concerns/controller.rb:9:in `<module:ViewToken>'
/Users/swaathi/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/the_comments-2.2.2/app/controllers/concerns/controller.rb:6:in `<module:TheComments>'
```

**Comment by the-teacher** [comment]
Hello, sorry, I have vacation. I will answer asap.

**Comment by the-teacher** [comment]
@swaathi hello. This problem usually related with `require` or `require_related` instructions in code. But I think I fixed, and it replaced with `authoload` instructions.

you can see it here

https://github.com/the-teacher/the_comments/blob/master/lib/the_comments.rb#L13

which version are you use? Can you install gem from master branch?

**Comment by swaathi** [comment]
That's great. Thanks for issuing a fix. I'll pull it from the master and get back to you. :)

**Comment by jakeatwork** [comment]
i just encountered the same issue, pulled down master, and sidekiq works fine. thanks!

**Comment by the-teacher** [comment]
looks fixed for @jakeatwork 
I hope it fixed in master
