### ISSUE TITLE
follow the installation guide failed with the_role gem installed

### ISSUE THREAD

**Issue by jerome2** [the-teacher/the_comments#41]
When you have the two gems (from your team) installed:
-the_role
-the_comments
and when follow the guide at part where you tell to define member function  "admin?" inside the user.rb model, then after that, the "the_role" function .admin? never works more like attempted:
simply, the fact is that only the user.first (if admin) could be recognize, never more an other one then the first user id in the database table. 
then for exemple, if i have an admin user with id != 1, then after login as admin user, the function tag: "current_user.admin?" (condition test for show something if admin is logged in) not works (return false but the user is an admin well configured). If i remove this admin? memeber function from user.rb model, then it works... but some other stuff from the_comment not... i would like the two gems to be able to works fine together (at the same time... lol).
I was tryed to explain you that in the issue for "the_role" gem, but i failed to make me understand.

please, could you try and test this way:
1 just follow your guide and install this way gem "the_role" and gem "the_comments"
2 then add an admin user (not the id 1) and/or two users "admin"
3 try to play with condition roles test and see the problem

at this time, i not find the solution, but maybe it is not difficult.
thanks

**Comment by the-teacher** [comment]
Hello, @jerome2 ! I will read this issue after 5 or 6 hours. I promise )) sorry, but right now I am busy

Thanks a lot for your help!

**Comment by jerome2** [comment]
you have time... no problem.
I try to just comment the user model admin? member function (and only this memeber function) and this seems to work (need more time to test full).
maybe you can just have a look later and wait more or close this issue comment if this resolve really this problem, maybe just add a comment in the guide will inform the newbies ones like me...
thanks.

**Comment by the-teacher** [comment]
@jerome2 

Let me try to explain. If you use THE ROLE you shouldn't re-implement `admin?` method. It implemented in the_role gem. Just remove your additional code for this.

Actually, you have to implement `comments_admin?` and `comments_moderator?`.  Nobody knows how you will do that. It's related with your task. 

```ruby
class User < ActiveRecord::Base
  include TheComments::User

  has_many :posts

  # IT'S JUST AN EXAMPLE OF ANY ROLE SYSTEM 
  def admin?
    self == User.first
  end

  # METHODS FOR THE-COMMENTS
  def comments_admin?
    admin?
  end

  def comments_moderator? comment
    id == comment.holder_id
  end
end
```

**Comment by jerome2** [comment]
yes that is: not implement the admin? memeber function.
I think it is something évident for you (and logic), but maybe you can add this in the guide for other newbies. I think it is not a bad idea to tell that (and it is just one line to add...).
thanks for your answer.

**Comment by the-teacher** [comment]
@jerome2 thank for your help and time!
