### ISSUE TITLE
StateMachine method redefined

### ISSUE THREAD

**Issue by viciousstar** [the-teacher/the_comments#44]
I use want add comment to Spree::Product, but Spree::Order is already modify StateMachine,so I accept some warnings.
**instance method "XXXX" is already defined in Spree::Order :state instance helpers, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true**
are there some simple method can solve this problem? thx

**Comment by the-teacher** [comment]
@viciousstar `instance method "XXXX" is already defined in Spree::Order :state instance helpers, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true` Sorry, but what? I have no ideas about it. Hm. I will try to think about it.

**Comment by viciousstar** [comment]
[This is the Spree code](https://github.com/spree/spree/blob/a9bf9a920b9c10a76f63606e0e9c60716104606c/core/app/models/spree/order/checkout.rb#L46)
[This is your code](https://github.com/the-teacher/the_comments/blob/e3a0ece4bfa3dd784fa0382a28ebe013e41db327/app/models/concerns/the_comments/comment_states.rb#L7)
I do not know how state_machine works, there is any conflict?

**Comment by the-teacher** [comment]
you do something wrong.
My state machine should works with comments, but not with Orders (in your case).

Looks like you wrote something like this:

```ruby
class Order
  include TheComments::CommentStates
end
```

or maybe

```ruby
class SomeNameOfClass
  include Spree::Order::Checkout
  include TheComments::CommentStates
end
```

so, you should to study your code and find misconception

**Comment by viciousstar** [comment]
Thanks for your help, It's my wrong.

**Comment by the-teacher** [comment]
@viciousstar awesome! thank you for your feedback! good luck!
