### ISSUE TITLE
How to use this gem in specific namespace

### ISSUE THREAD

**Issue by khacluan** [the-teacher/the_comments#47]
I want to use this gem in my applications, but I want to restructure in module such as ```Forum```
How can I do it ?

**Comment by the-teacher** [comment]
Hello! What problems did you meet? Can you describe it in more detail?

**Comment by khacluan** [comment]
Yes, I added the_comments gem into my exist application, and I have exists comment model before
And now I want to create and use this gem in a namespace , for example: ```Forum```
Have you any idea ?

**Comment by the-teacher** [comment]
gem is not ready for work with app which already have Comment model. It is intersection. And it's not good of course

The only way which I know for your case - is build you forum as isolated engine

**Comment by khacluan** [comment]
thanks for reply!
