### ISSUE TITLE
not really an issue, but a technical question

### ISSUE THREAD

**Issue by jerome-diver** [the-teacher/the_comments#51]
I like the_comments gem, also thank you for this great gem application.
I see that it use awsome_nested_set gem for running, but i would like to use closure_tree for make clean model trees constructions (after look at these gems together, i think that closure_tree shuould be, in may case; better to use for me). But then... could it be possible to use these two gems together ?
the_comments and then... "comments" machanism is used by awsome_nested_set. But if an other model (for exemple: "Album" use closure_tree, and "Album" has comments linked. This should become a problem or not ?

**Comment by the-teacher** [comment]
@jerome-diver hello!
TheComments based on TheSortableTree gem.

The most important part of this gem is render helper for fast rendering of tree.
https://github.com/the-teacher/the_sortable_tree/blob/master/app/helpers/the_sortable_tree_helper.rb

This helper based on `parent_id` field. This is most important part of this helper. As I can see `closure tree` based on the same field.

Probably you can use them together, but there is no any warranty. It's not tested. And maybe it will take a while to force them work together. I have no experience in it, I can't be sure, sorry.
