### ISSUE TITLE
Copy/Move thread

### ISSUE THREAD

**Issue by trubachev** [the-teacher/the_comments#55]
Is there as easy way to copy/move all comments to another commentable?

**Comment by the-teacher** [comment]
@trubachev hey! Hello and sorry for delay, there are a lot of messages in my email box and activity feed in GH, sometimes I just don't notice some messages. Sorry again.
Well. I think no, there is no a way to do that. The only way right now is using rails console.

And also this gem is a bit abandoned - please check another one solution please.

https://github.com/TheComments/dummy_app
https://github.com/TheComments
