### ISSUE TITLE
I get this JS error when posting a comment

### ISSUE THREAD

**Issue by ajn123** [the-teacher/the_comments#58]
![image](https://user-images.githubusercontent.com/2382277/27757702-985eb86c-5dca-11e7-8873-8caf0321f269.png)

It seems to be happening here: 
![image](https://user-images.githubusercontent.com/2382277/27757709-b4d7176e-5dca-11e7-9066-51d16d0d0438.png)

I don't know how to really tackle this one.

**Comment by the-teacher** [comment]
Hey! Hello! `.errors` is the field in your AJAX response.
Please open `Network` tab, find a request to a server and make a screenshot of AJAX response.
Maybe you just have a server side error.

**Comment by ajn123** [comment]
I had to delete the ralis 5 rails-ujs
